{% set name = "realtime" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4071b095d7f750fcd68ec322e05045fce067b5cd5309a7ca809fcc87e50f56a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - aiohttp >=3.10.2
    - python-dateutil >=2.8.1
    - typing-extensions >=4.12.2
    - websockets >=11,<13

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - realtime

about:
  home: https://github.com/supabase-community/realtime-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Client for Phoenix Channels
  description: |
    A Python Client for Phoenix Channels

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
